---
#-------------------------------
# General Site Settings

title: JuYeong Hwang
logo:
author: JuyeongHwang
description: this is meta description
email: 05judy02[at.]gmail.com
github: https://github.com/JuyeongHwang
# phone: +880 2544 658 256
# address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com) / Modified by [tjswodud](https://github.com/tjswodud)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: CV, link: "/cv" }

#-------------------------------
# Hero Section

social:
  - { icon: "ti-github", link: "https://github.com/JuyeongHwang" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/주영-황-89b165332?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"}

#-------------------------------
# About (Section and Page)

# About Section
blurb: <li>Keep making steady efforts at my own pace</li><li>Do not settle for the present</li><li>Live a happy life</li>

blurb-btn-link: "/about"
blurb-btn-name: know more

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: B.S. in Software Convergence,
      url: "",
      date: "Mar. 2019 ~ Aug. 2023",
      organization: "Department of Software Convergence, <br> Kyung Hee University",
    }
  - {
      name: Integrated M.S./Ph.D. in Computer Science,
      url: "",
      date: "Aug. 2023 ~",
      organization: "School of Computer Science and Engineering, <br> Korea University",
    }

#-------------------------------
# Publication Section
pubs-title: Publications
pubs:
- {
    title-kor: "BiPO: Bidirectional Partial Occlusion Network for Text-to-Motion Synthesis",
    authors: "Seong-Eun Hong, Soobin Lim, <b>Juyeong Hwang</b>, Minwook Chang, HyeongYeop Kang†",
    conference: "The IEEE/CVF Winter Conference on Applications of Computer Vision (WACV), Mar. 6–10 2026, Tucson, Arizona, United States",
    url: "https://doi.org/10.48550/arXiv.2412.00112"
  }
- {
    title-kor: "How Does a Virtual Agent Decide Where to Look? Symbolic Cognitive Reasoning for Embodied Head Rotation",
    authors: "<b>Juyeong Hwang<sup>1</sup></b>, Seong-Eun Hong<sup>1</sup>, JaeYoung Seon, HyeongYeop Kang*",
    conference: "ACM SIGGRAPH Asia, Dec. 15–18 2025, Hong Kong",
    url: "https://arxiv.org/pdf/2508.08930"
    # url: "https://doi.org/10.1145/3757377.3763849"
  }
#-------------------------------
# Patient Section
patient-title: Patents

patient:
  - {
      name-kor: "System and method for generating daily activity plans for virtual agents",
      description: "Brief description text"
    }
  - {
      name-kor: "Method and system for determining head rotation based on gaze of a cognitive agent",
      description: "Another brief description text"
    }
#-------------------------------
# Awards Section
awards-title: Awards
awards:
- {
  name-kor: "2023 Software Festival, Excellence Award",
  description: "."
}
- {
    name-kor: "2020 KHUTHON, Grand Prize",
    description: " "
  }

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  engines:
    - {
        name: Unreal Engine,
        icon: "unreal.png",
      }
    - {
        name: Unity,
        icon: "unity.png",
      }
  languages:
    - {
        name: Python,
        icon: "python.png",
      }
    - {
        name: C++,
        icon: "cpp.png",
      }
    - {
        name: C#,
        icon: "csharp.png",
      }

#-------------------------------
# Exprerience Section

experience-title: Experiences
experience:

  - {
      name: KIST,
      icon: "kist.png",
      date: "Jun. 2022 ~ Aug. 2022",
      organization: "Korea Institute of Science and Technology (KIST)",
    }
  - {
      name: Researcher,
      icon: "iiixr.png",
      date: "Nov. 2022 ~",
      organization: "IIIXR LAB",
    }
  - {
    name: NC Fellowship,
    icon: "ncsoft.png",
    date: "Jan. 2023 ~ Feb. 2023",
    organization: "NCSOFT",
  }
  - {
      name: Pearl Abyss X Kyung Hee Univ. SW Convergence Talent Training Program,
      icon: "pearl_abyss.png",
      date: "Sep. 2022 ~ Jan. 2023",
      organization: "Pearl Abyss",
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - {
      name: UNTACT,
      image: "assets/images/portfolio/portfolio_1.png",
      url: "https://github.com/CompileBlue/UNTACT_SurvivalGame",
      description: Unity / 2D / Survival
    }
  - {
    name: NUCLAIN,
    image: "assets/images/portfolio/portfolio_2.png",
    url: "https://www.youtube.com/watch?v=VCABVM0x_VI&list=PL9EsG3LxiqRlG40YvzqvrN4Lj__fayzKn",
    description: Unreal / 3D / Survival
  }
  - {
    name: Performance improvement of text-based 3D motion generation using a mixture-of-experts architecture,
    image: "assets/images/portfolio/portfolio_9.png",
    url: "https://doi.org/10.15701/kcgs.2025.31.3.109",
    description: Character Animation / Text to Motion
  }

portfolio-link: /portfolio
portfolio-btn-name: know more

# Portfolio Page
portfolio-label:
  - { title: "Game Development", type: "game" }
  - { title: "Projects", type: "project" }
  - { title: "Research", type: "research" }

portfolio-items:
  - name: LoL Highlight Extractor
    portfolio-type:
      - type: "project"
    image: "assets/images/portfolio/portfolio_3.png"
    url: "https://github.com/SWTube/LoL-eSports-Highlight-Extractor"
    description: Python / Data Analysis
  - name: UNTACT
    portfolio-type:
      - type: "game"
    image: "assets/images/portfolio/portfolio_1.png"
    url: "https://github.com/CompileBlue/UNTACT_SurvivalGame"
    description: Unity / 2D / Survival
  - name: Game Engine Development
    portfolio-type:
      - type: "project"
    image: "assets/images/portfolio/portfolio_4.png"
    url: "https://github.com/SWTube/Darkest-Cave"
    description: C++ / Game Engine
  - name: NUCLAIN
    portfolio-type:
      - type: "game"
    image: "assets/images/portfolio/portfolio_2.png"
    url: "https://www.youtube.com/watch?v=VCABVM0x_VI&list=PL9EsG3LxiqRlG40YvzqvrN4Lj__fayzKn"
    description: Unreal / 3D / Survival
  - name: Image to 3D mesh
    portfolio-type:
      - type: "research"
    image: "assets/images/portfolio/portfolio_6.png"
    url: "https://www.youtube.com/watch?v=GLTibic-gIE&list=PL9EsG3LxiqRn1NAcdW1XBsDpuKWblhFHi"
    description: PyTorch / Deep Learning
  - name: DX11 Programming
    portfolio-type:
      - type: "project"
    image: "assets/images/portfolio/portfolio_5.png"
    url: "https://github.com/tjswodud/GameGraphicProgramming_2020105708_JaeYoungSeon"
    description: C++ / DirectX / Graphics
  - name: Action Game Development using NSM
    portfolio-type:
      - type: "research"
    image: "assets/images/portfolio/portfolio_7.png"
    url: "https://www.youtube.com/watch?v=idu3chKBKAs"
    description: Unity / Deep Learning
  - name: Realistic Character Control<br>using Motion VAE
    portfolio-type:
      - type: "research"
    image: "assets/images/portfolio/portfolio_8.png"
    url: "https://www.youtube.com/watch?v=SGoXMTo-asY"
    description: Character Animation / Deep Learning
  - name: Performance improvement of text-based 3D motion generation using a mixture-of-experts architecture
    portfolio-type:
      - type: "research"
    image: "assets/images/portfolio/portfolio_9.png"
    url: "https://doi.org/10.15701/kcgs.2025.31.3.109"
    description: Character Animation / Text to Motion

#-------------------------------
# CV (Section and Page)

cv-link: /cv
